name: CMake Test

on:
  push:
    branches:
      - workflow-setup
  pull_request:
    branches:
      - workflow-setup

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up DIM
      run:  |
        sudo chmod +x ${PWD}/test/dim-minimal/bin/dns
        export LD_LIBRARY_PATH=${PWD}/test/dim-minimal/lib:$LD_LIBRARY_PATH
        export PATH=${PWD}/test/dim-minimal/bin/:$PATH
        
    - name: Run in-container-test
      run: ./test/in-container-test/in-container-test.sh

